# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$all\
$git_branch\
$git_status\
$character
"""

[character] # The name of the module we are configuring is 'character'
success_symbol = '[>](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[X](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = ' '
style = "bold purple"
truncation_length = 40
truncation_symbol = ''

[azure]
disabled = false
format = '[$symbol($subscription | $username)]($style) '
symbol = '󰠅 '
style = 'blue bold'

[azure.subscription_aliases]
AZ-AS-SUB-EX-N-SEQ01561-DE-Deployment-Engine-DEV = "01561 (sandbox)"
AZ-AS-SUB-EX-N-SEQ01572-DE-Deployment-Engine-DEV = "01572 (dev)"
AZ-AS-SUB-EX-N-SEQ02332-DE-Deployment-Engine-DEV = "02332 (ci)"

[terraform]
disabled = true
