[tools]
terraform = "latest"
"vfox:neovim" = "latest"
gh = "latest"
lazygit = "latest"
lazydocker = "latest"
just = "latest"
ripgrep = "latest"
uv = "latest"
azure-cli = 'latest'
# langs
node = 'latest'
python = 'latest'
go = 'latest'
powershell-core = "latest"
# term
"github:herdrdev/herdr" = 'latest'
"github:can1357/oh-my-pi" = 'latest'
